"""add_has_error_to_signal

Revision ID: 87d703529f1e
Revises: 8cd71ba66070
Create Date: 2026-07-04 12:07:54.605504
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '87d703529f1e'
down_revision: Union[str, None] = '8cd71ba66070'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signals', sa.Column('has_error', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signals', 'has_error')
    # ### end Alembic commands ###
