"""add_data_error_count_data_source_universe_source_to_strategy_run

Revision ID: 8cd71ba66070
Revises: 
Create Date: 2026-07-04 11:40:48.333515
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '8cd71ba66070'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategy_runs', sa.Column('data_error_count', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.add_column('strategy_runs', sa.Column('data_source', sa.String(length=50), nullable=True))
    op.add_column('strategy_runs', sa.Column('universe_source', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategy_runs', 'universe_source')
    op.drop_column('strategy_runs', 'data_source')
    op.drop_column('strategy_runs', 'data_error_count')
    # ### end Alembic commands ###
